### ISSUE TITLE
商品数据表，价格的存储，为什么小数点要单独设置一属性？

### ISSUE THREAD

**Issue by zhuxubin** [skr-shop/manuals#16]
作者你好，有个数据库设计的问题想了解一下，为什么商品价格数据表设计部分，小数部分要单独存储，这是出于什么考虑？
![image](https://user-images.githubusercontent.com/19299867/57499112-fcd50280-7310-11e9-8510-73928c50545a.png)

**Comment by TIGERB** [comment]
金额存整型 避免各种浮点数计算的坑

**Comment by baijunyao** [comment]
存整型没问题； @zhuxubin  是想问： 为什么要单独设计一个字段用来存小数部分吧？  
疑惑 +1 ； price_fee 的单位是 `元` 还是 `分` ？ 如果存整型； 直接用一个字段以  `分` 为单位来存储金额就可以吧？

**Comment by TIGERB** [comment]
有的国家没有分的概念

**Comment by helei112g** [comment]
有的国家一般取2位，有的国家会取3或者其它小数位数

**Comment by baijunyao** [comment]
好的；明白了；多谢；
