### ISSUE TITLE
transaction_id和transaction_code区别和作用

### ISSUE THREAD

**Issue by cowsky** [skr-shop/manuals#17]
`transaction_id` VARCHAR(64) NOT NULL COMMENT '系统唯一识别交易号',
 `transaction_code` VARCHAR(64) NOT NULL COMMENT '支付成功时，该笔交易的 code',

支付系统中这两个字段的区别和作用在哪里呢？

**Comment by helei112g** [comment]
`transaction_id` 是用来标记本笔交易在自己的系统中唯一交易号。`transaction_code` 是自己向第三方（支付宝、微信等）发起支付请求时，传给第三方的。
这样设计有几个目的：
1. 个别第三方一个交易号只能发起一次支付请求；
2. 可以非常清晰的处理重复支付问题；
3. 对总的发起过的支付次数&路径便于分析。

**Comment by cowsky** [comment]
谢谢回复，那我可以理解为一个transaction_id对应多个transaction_code么？那我有个疑问哈
是否每次支付请求都生成一个新的transaction_code（不重复）来解决重复支付问题，如果真的是重复提交支付请求并重复支付了，那么解决退款问题呢，具体退哪一笔？还有，这样如果用户重复多次申请支付，是不是导致transaction_code膨胀？

**Comment by helei112g** [comment]
第一个问题： 一个 `transaction_id` 与 `transaction_code` 确实是一对多的关系。你可以再看下 
**pay_transaction_extension** 这张表的注释。

第二个问题： 重复支付后具体退哪一笔？如果用户支付了两笔，你肯定会收到两个异步通知，那么最后收到的异步通知视为重复支付，对其进行退款。可以看这张表 **pay_repeat_transaction**。

第三个问题：关于膨胀的问题，可以对code设置一个生成次数，比如：2^6。因为一般超过这么多次还在发起请求要么是恶作剧，要么你支付服务出了故障。

上面三个问题都非常好，部分内容由于文章结构考虑没有说到这么细，感谢你的提问。

**Comment by itcuihao** [comment]
>商户支付的订单号由商户自定义生成，仅支持使用字母、数字、中划线-、下划线_、竖线|、星号*这些英文半角字符的组合，请勿使用汉字或全角等特殊字符。微信支付要求商户订单号保持唯一性（建议根据当前系统时间加随机序列来生成订单号）。重新发起一笔支付要使用原订单号，避免重复支付；已支付过或已调用关单、撤销（请见后文的API列表）的订单号不能重新发起支付。

来自[微信参数规定](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=4_2)

什么情况下一个交易号，要多次发送支付请求呢？

看微信里使用原订单单号，避免重复支付。

想请教下，这里的重复支付的设置是怎么考量的呢？

**Comment by helei112g** [comment]
你这里转换一个思路。把自己开发的支付网关想成就是第三方支付。
当业务应用请求支付网关的时候，业务方同一个订单肯定还是给你相同的订单号，无论请求你多少次。

然后假设你就是微信，那么你调用银行的时候，给银行可能就是每笔交易都是一个新的交易号，也可能是同一个。但是这里为了确保对接渠道某种程度上的一致性，我们用都采用新的交易号方式来统一这种行为。
