### ISSUE TITLE
能透露下手册的图是用什么工具画的吗？

### ISSUE THREAD

**Issue by skcai** [skr-shop/manuals#2]
能透露下手册的图是用什么工具画的吗？这个项目很不错，非常有参考价值，感谢你们的付出！

**Comment by TIGERB** [comment]
1. 原型：Balsamiq Mockups 3
2. mysql建模： mysql workbench
3. 其他：processon

**Comment by skcai** [comment]
谢谢！

**Comment by TIGERB** [comment]
客气～ 互相学习～
