### ISSUE TITLE
spu->sku

### ISSUE THREAD

**Issue by WuJiY** [skr-shop/manuals#22]
在后端表现是 一个spu必须插入一条sku吗  如果当前spu没有其他属性的情况下 ，还是说如果没有sku就不需要插入sku表

**Comment by TIGERB** [comment]
在后端表现是 一个spu必须插入一条sku吗
---------
不是

**Comment by WuJiY** [comment]
ok  明白了  就是有sku的情况下 在插入到sku 表，有些产品如果不需要sku的 比如什么水果 单独这么一种产品 就直接一个spu 就OK了

**Comment by TIGERB** [comment]
你可能理解错我意思了
----
销售的一定是SKU(Stock Keep Unit)
----
创建一个Spu和Sku是两个过程，只是创建spu时不一定要创建一个sku, 但是创建sku却是基于spu创建出来的

**Comment by WuJiY** [comment]
创建有多个sku的产品这个应该没什么问题 理解一样

但如果单纯的创建一个spu 时
比如：现在创建一个产品（冰糖心苹果）那我肯定是插入spu表苹果的相关信息，我的理解是这里就不需要插入sku表（因为没有其他sku了，这里是不是就是你说的 `只是创建spu时不一定要创建一个sku`），那么销售的时候 怎么算这个是一个sku？（2，你意思是也要插入一条关联数据进sku表？）

不知道有没有表达清楚

**Comment by TIGERB** [comment]
你想想 你最后商品上架销售的是sku不是spu是不是就明白了

**Comment by liuxingke** [comment]
我这里也有疑问，像图书一类的商品一般是没有规格属性的，这种商品怎么添加sku？如果不添加sku，那下单时怎么处理？
