### ISSUE TITLE
关于购物车存储

### ISSUE THREAD

**Issue by WuJiY** [skr-shop/manuals#23]
不知道购物车放入redis 是怎么设计的？
我看现在很多方案是  hmset  id  product count  这么个结构  
我不知道这边的方案是怎样的 ？什么样的方式存储到redis

**Comment by helei112g** [comment]
下一篇就会将这些，请耐心等待

**Comment by WuJiY** [comment]
好的 学习

**Comment by WuJiY** [comment]
> 下一篇就会将这些，请耐心等待

购物车还会更新吗？

**Comment by TIGERB** [comment]
会 正在写

**Comment by WuJiY** [comment]
好 谢谢



在 2019-12-22 09:24:48，"Zhan Shi" <notifications@github.com> 写道：

会 正在写
