### ISSUE TITLE
支付流水表和退款表中的transaction_id是否需要一致？

### ISSUE THREAD

**Issue by elricli** [skr-shop/manuals#43]
问题一：同个订单，支付之后申请退款，那退款表（pay_refund）中的transaction_id是否需要和支付流水表（pay_transaction）中的transaction_id一致？

问题二：退款表中的transaction_id的用处？如果是标记退的支付流水表的哪条订单数据，字段名修改为pay_transaction_code或transaction_code是否更合适？

**Comment by helei112g** [comment]
问题一：pay_refund.transaction_id == pay_transaction.transaction_id。这里肯定是要吃一致，一致的目的是你可以追溯一笔交易总计退了多少。

问题二：严格来说，仅仅是数据关联用 transaction_code 也没有问题。但是整体看，你会发现所有的表与表之间的关联都是通过 transaction_id 来做的。

**Comment by cullenx** [comment]
还有个用途 用id 后续分库分表后&nbsp; 涉及这个字段的多表join 比较好做 可以落到一个分库上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 下午2:31
收件人: "skr-shop/manuals"<manuals@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [skr-shop/manuals] 支付流水表和退款表中的transaction_id是否需要一致？ (#43)





 
问题一：pay_refund.transaction_id == pay_transaction.transaction_id。这里肯定是要吃一致，一致的目的是你可以追溯一笔交易总计退了多少。
 
问题二：严格来说，仅仅是数据关联用 transaction_code 也没有问题。但是整体看，你会发现所有的表与表之间的关联都是通过 transaction_id 来做的。

**Comment by elricli** [comment]
好的，了解了~
