### ISSUE TITLE
账户服务数据库表相关疑问

### ISSUE THREAD

**Issue by jack-fd** [skr-shop/manuals#45]
最近在学习skrshop设计，发现一些疑惑，希望得到大佬们的帮助；
1、auth_role_staff与auth_role缺少关联关系，或者没理解设计；
2、auth_role、auth_role_staff使用了text类型，数据库设计应该不建议使用text类型；
3、account_user、staff_info都出现email、phone，感觉staff_info可去掉;

**Comment by TIGERB** [comment]
1. `staff_id` 对应的是哪个员工；`role_set` 存`auth_role`.`id`，给员工关联上角色。
2. 不建议使用`text`类型，不代表不能用。现在这是个相当于后台系统的表，没有很大的数据量和请求量，所以该场景下可以使用。
3. `staff_info`的`email`、`phone`是冗余的设计，不建议去掉，因为`staff_info`的`email`是员工的企业邮箱；`account_user`的`email`是企业下互联网应用的账号注册时的邮箱或绑定的个人邮箱；`phone`同样的道理，员工的账号可以换绑其他手机号，同时增加了灵活性。

**Comment by WuJiY** [comment]
1、是否可以将role_set字段 直接设置在staffs员工表里 或者说 单独设置个auth_role_staff 表 是怎样的考量

**Comment by WuJiY** [comment]
> 关联
补充：第一条
如果单独使用个auth_role_staff 表 是不是应该设置为多对多的关系
role_id int
staff_id int

**Comment by WuJiY** [comment]
> 1、是否可以将role_set字段 直接设置在staffs员工表里 或者说 单独设置个auth_role_staff 表 是怎样的考量


关联
补充：第一条
如果单独使用个auth_role_staff 表 是不是应该设置为多对多的关系
role_id int
staff_id int

**Comment by TIGERB** [comment]
可以加一个角色组的表，对应不同角色的集合

**Comment by WuJiY** [comment]
> 可以加一个角色组的表，对应不同角色的集合

是否可以更新完善到文档里 🤔

**Comment by TIGERB** [comment]
欢迎 Merge Request哈～
