### ISSUE TITLE
商品模块问题

### ISSUE THREAD

**Issue by fangyoukeji** [skr-shop/manuals#57]
在商品模块数据库设计中有一个sku库存表 `product_sku_stock`,但是库存明显是可以合并到sku表 `product_sku`中，单独见一个表，开销也会很大啊，建它的理由是啥呢

**Comment by TIGERB** [comment]
基础商品信息和库存信息解耦合，初期库存概念比较简单，后期库存会逐步复杂化。比如销售库存(可售库存、锁定库存等等)、实物库存；渠道库存等等
