### ISSUE TITLE
图片失效了

### ISSUE THREAD

**Issue by XiaoanHi** [skr-shop/manuals#59]
![image](https://user-images.githubusercontent.com/26805776/209514486-18a7a811-b4f7-4025-9c9b-121a0c451e8a.png)
![image](https://user-images.githubusercontent.com/26805776/209514632-e17a9999-3363-4678-98ad-6a7159c1f80b.png)
设置代理后依然无法访问

**Comment by TIGERB** [comment]
哦 域名备案 失效了 我处理下 感谢反馈

**Comment by TIGERB** [comment]
临时恢复了  先用http协议访问哈  http://skrshop.tech/#/

**Comment by YuanLi001** [comment]
前言图片失效
![image](https://user-images.githubusercontent.com/74064276/216307017-6ad4de1d-080e-4b49-bb43-904dc9cf119c.png)

**Comment by TIGERB** [comment]
已恢复，更换到腾讯云cos图床。优惠券部分恢复中
