### ISSUE TITLE
表模型设计中create_at类型为什么是int？

### ISSUE THREAD

**Issue by huang-x-h** [skr-shop/manuals#6]
```sql
`create_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
`update_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
```

时间类型不是一般都用 `Date` 或者 `Timestamp` 吗

**Comment by helei112g** [comment]
方便跨时区管理

**Comment by huang-x-h** [comment]
@helei112g 能否举个例子，`create_at` 值是什么样的。跨时区方案，一般是数据库记录零时区时间，根据用户所在时区做转化吧

**Comment by TIGERB** [comment]
- timestamp 得确很方便，但是有范围限制 1970-01-01 00:00:01  ～ 2038-01-19 03:14:07

- datetime 8字节， int 4字节  ，既然能达到相同的目的，那必然选择存储空间更小的int，其次也许int索引的效率更高（需要验证）

最后一个小理由：int更加灵活。int在应用层去控制时间展示的格式，相对于datetime直接统一写死数据库更加灵活，比如单个机房对应多个国家或多应用，每个国家或应用具有不同时间展示格式

**Comment by huang-x-h** [comment]
@TIGERB 存储值是类似 `Date.now()` `1543409677640` ? 为什么定义 `int(11)` 默认值吗？

**Comment by TIGERB** [comment]
int(11)的含义:

int 声明了数据类型，储存空间4字节，1字节８位，所以int可以存储值的范围：unsigned无符号 0 ~ 2^32-1 ;signed有符号 -2^16 ~ 2^16 - 1 

(11) 声明了length(注意和储存无关)，但是length只是在int 设置为zerofill时生效。举个例子：

id int(3) zerofill auto_increment 自增主键的的第一个值为 001

**Comment by huang-x-h** [comment]
@TIGERB 感谢解惑
