### ISSUE TITLE
请问 员工如何登陆？

### ISSUE THREAD

**Issue by lyg00702** [skr-shop/manuals#9]

**Comment by TIGERB** [comment]
通用的登录逻辑。

能否访问后台，是权限的逻辑。

**Comment by lyg00702** [comment]
员工是通过注册方式加入的，还是由账户的管理员添加自己的员工？

**Comment by TIGERB** [comment]
都可以。

最终uid都是通过“账号服务”的注册接口获取的。

**Comment by lyg00702** [comment]
是否允许一个员工从属于多家网店账号？

**Comment by TIGERB** [comment]
目前的架构还属于 B2C。

C2C需要引入”商家“的概念了。后期会接入”商家“。

**Comment by astraw99** [comment]
嗯，年后会引入商家，C2C实现一个用户可申请开一个或多个店铺、自主发布管理商品、收款、结算等。

**Comment by lyg00702** [comment]
谢谢你们的热情解答。
